const colors = {
  light: {
    text: "#2C2128",
    tint: "#D44F79",
    background: "#FAF5F7",
    foreground: "#2C2128",
    card: "#FFFFFF",
    cardForeground: "#2C2128",
    primary: "#D44F79",
    primaryForeground: "#FFFFFF",
    secondary: "#F2EAED",
    secondaryForeground: "#2C2128",
    muted: "#F2EAED",
    mutedForeground: "#7A6370",
    accent: "#E07848",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E2D5D9",
    input: "#E2D5D9",
  },
  dark: {
    text: "#FAFAFA",
    tint: "#D44F79",
    background: "#241820",
    foreground: "#FAFAFA",
    card: "#291F24",
    cardForeground: "#FAFAFA",
    primary: "#D44F79",
    primaryForeground: "#FFFFFF",
    secondary: "#3D2F35",
    secondaryForeground: "#FAFAFA",
    muted: "#3D2F35",
    mutedForeground: "#BBA8B0",
    accent: "#E07848",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#3D2F35",
    input: "#3D2F35",
  },
  radius: 8,
};

export default colors;
